version: '3'

services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "8080:8080"
    networks:
      - mern-network
    environment:
      - REACT_APP_API_URL=http://server:8080/api

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "3030:3030"
    networks:
      - mern-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_ecommerce
    depends_on:
      - mongodb  # Server depends on MongoDB

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db
    # Optionally, you can add a healthcheck here for MongoDB

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally

