pipeline {
    agent any  // Specifying the agent where the pipeline will run

    environment {
        Git_URL = 'https://github.com/Aman-0308/Devops-project.git'  // Storing Git url to ennviroment variable
    }

    stages {
        stage("Checkout SCM") {
            steps {
                echo "Cloning Git repo"
                checkout scm
                echo "Git clone successful"
            }
        }

        stage("Build") {
            parallel {
                stage("Build Frontend") {
                    steps {
                        echo "Building Frontend Docker Image"
                        sh """
                            cd Mern-CICD/mern/frontend
                            docker build -t mern-frontend:V1 .
                        """
                        echo "Frontend Docker build successful"
                    }
                }
                stage("Build Backend") {
                    steps {
                        sh "cd Mern-CICD/mern/backend"
                        sh "docker build -t mern-backend:V1 ./Mern-CICD/mern/"
                        echo "Backend Docker build successful"
                    }
                }
            }
        }

        stage("Push Images to Docker Hub") {
            steps {
                echo "Logging into Docker Hub"
                withCredentials([usernamePassword(credentialsId: 'Dockerhub', passwordVariable: 'DOCKERHUB_PASS', usernameVariable: 'DOCKERHUB_USER')]) {
                    // Use env to explicitly reference variables in shell commands
                    // Dockerhub credentials needs to be added as global variable under manage jenkins --> crendetails >> add global variable.
                    echo "Docker login to Docker Hub"
                    sh """
                        docker login -u ${env.DOCKERHUB_USER} -p ${env.DOCKERHUB_PASS}
                    """

                    echo "Pushing Frontend Docker image"
                    sh """
                        docker tag mern-frontend:V1 ${env.DOCKERHUB_USER}/mern-frontend:V1  // Image has to be tag to dockerhub
                        docker push ${env.DOCKERHUB_USER}/mern-frontend:V1
                    """

                    echo "Pushing Backend Docker image"
                    sh """
                        docker tag mern-backend:V1 ${env.DOCKERHUB_USER}/mern-backend:V1  // Image has to be tag to dockerhub
                        docker push ${env.DOCKERHUB_USER}/mern-backend:V1
                    """
                }
            }
        }
        stage("Deploy") {
            steps {
                echo "Deploying"
                // Add your deployment steps here (e.g., SSH into a server, Docker run, etc.)
            }
        }
    }
}

