pipeline {
    agent any  // Specifying the agent where the pipeline will run

    environment {
        Git_URL = 'https://github.com/Aman-0308/Devops-project.git'  // Corrected the syntax for Git URL
        Docker_credentials = 'Dockerhub'  // Corrected environment variable
    }

    stages {
        stage("Build") {
            parallel {
                stage("Build frontend") {
                    steps {
                        sh "docker build -t mern-frontend:V1 ./Mern-CICD/mern/frontend"
                        echo "Frontend Docker build successful"
                    }
                }
                stage("Build Backend") {
                    steps {
                        sh "docker build -t mern-backend:V1 ./Mern-CICD/mern/backend"
                        echo "Backend Docker build successful"
                    }
                }
            }
        }

        stage("Push images to Docker registry") {
            steps {
                // Login to Docker Registry using Jenkins credentials
                echo "Logging into Docker Hub"
                withCredentials([usernamePassword(
                    credentialsId: 'Dockerhub', 
                    passwordVariable: 'Dockerhub-pass', 
                    usernameVariable: 'Dockerhub-user')]) {
                    sh "docker login -u $Dockerhub-user -p $Dockerhub-pass"

                    // Pushing Frontend image
                    sh "docker tag mern-frontend:V1 $Dockerhub-user/mern-frontend:V1"
                    sh "docker push $Dockerhub-user/mern-frontend:V1"
                    echo "Frontend image pushed successfully"

                    // Pushing Backend image
                    sh "docker tag mern-backend:V1 $Dockerhub-user/mern-backend:V1"
                    sh "docker push $Dockerhub-user/mern-backend:V1"
                    echo "Backend image pushed successfully"
                }
            }
        }
        stage("Deploy") {
            steps {
                echo "Deploying"
                // Add your deployment steps here (e.g., SSH into a server, Docker run, etc.)
            }
        }
    }
}

