
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          name: metrics
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
          requests:
            memory: 50Mi
            cpu: 50m
        volumeMounts:
        - name: node-exporter-proc
          mountPath: /host/proc
          readOnly: true
        - name: node-exporter-sys
          mountPath: /host/sys
          readOnly: true
        args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
      volumes:
      - name: node-exporter-proc
        persistentVolumeClaim:
            claimName: monitoring-pvc
      - name: node-exporter-sys
        persistentVolumeClaim:
            claimName: monitoring-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: node-exporter
  ports:
  - port: 9100
    targetPort: metrics
