apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerService
  namespace: epharmacy
  labels:
    app: customerService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerService
  template:
    metadata:
      labels:
        app: customerService
        role: backend
    spec:
      serviceAccountName: default  
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      tolerations:
        - key: "nodeType"
          operator: "Equal"
          value: "Node01"
          effect: "NoSchedule"
      nodeSelector:
        node-type: Node01
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodeType
                    operator: In
                    values:
                      - Node01
      containers:
        - name: authService
          image: your-image-name:tag  # You must specify an image here
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6500
          envFrom:  
            - configMapRef:
                name: customer-config
            - configMapRef:
                name: backend-config
            - secretRef:
                name: customer-secret
            - secretRef:
                name: backend-secret
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"  
          readinessProbe:
            httpGet:
              path: /health
              port: 6500
            initialDelaySeconds: 120
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 6500
            initialDelaySeconds: 200
            periodSeconds: 10

---
apiVersion: v1
kind: service
metadata:
  name: customerService
  namespace: epharmacy
  labels:
    app: customerService
spec:
  type: ClusterIP             # other types are NodePort, LoadBalancer
  ports: 
      - name: HTTP
        port: 80
        targetPort: 6500
        protocol: TCP
      - name: HTTPS
        port: 443
        targetPort: 6500
        protocol: TCP  
      # nodePort: 30000   - If using NodePort, specify the port number.                
  selector:
    app: customerService
    role: backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-config
  labels:
    app: Epharmacy-application  
data:
  server.servlet.context-path: "/epharmacy/customer"
  baseUrl: "http://customer-service:6500/epharmacy/customer/customer-api"
 
---