apiVersion: apps/v1
kind: Deployment
metadata:
  name: Epharmacy-frontend
  namespace: Epharmacy
  labels:
    role: frontend
spec:
  replicas: 2
  selector: 
    matchLabels:
      role: frontend
  template: 
    metadata:
      name: Epharmacy-frontend
      labels:
        role: frontend
    spec:
      serviceAccountName: default
      securityContext:
        runAsUser: 1000               # Non-root user ID
        runAsNonRoot: true
      tolerations:
        - key: "nodeType"
          operator: "Equal"
          value: "Node01"
          effect: "NoSchedule"
      nodeSelector:
        node-type: Node01
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "nodeType"
                    operator: In
                    values:
                      - "Node01"
      containers:
        - name: frontendService
          image: your-image:tag  # Replace with actual image
          ports:
            - containerPort: 6200
          envFrom:
            - configMapRef:
                name: frontend-configmap
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1.5Gi"
              cpu: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 6200
            initialDelaySeconds: 120
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 6200
            initialDelaySeconds: 200
            periodSeconds: 10
---
apiVersion: v1
kind: service
metadata:
  name: frontendService
  namespace: Epharmacy
labels:
    role: frontend
spec:
  type: ClusterIP             # other types are NodePort, LoadBalancer
  ports: 
      - name: HTTP
        port: 80
        targetPort: 6200
        protocol: TCP
      - name: HTTPS
        port: 443
        targetPort: 6200
        protocol: TCP  
      # nodePort: 30000   - If using NodePort, specify the port number.                
  selector:
    role: frontend

---
apiVersion: v1
kind: configmap
metadata:
  name: frontend-configmap
  app: Epharmacy-application
data:
  customerLoginUrl: "http://localhost:6100/epharmacy/customer-api/customer/login"
  getAllMedicinesUrl: "http://localhost:6200/epharmacy/medicine-api/medicines/pageNumber/"
  registerCustomerUrl: "http://localhost:6100/epharmacy/customer-api/customer/register"
  getCustomerCartUrl: "http://localhost:6100/epharmacy/customer-api/customer/cart/getCartDetails"
  
---
   