apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: Epharmacy-frontend-vpa
  namespace: Epharmacy  # Namespace where the VPA will be applied
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: Epharmacy-frontend
  updatePolicy:
    updateMode: "Auto"    # Options: Off / Initial / Auto
  resourcePolicy:
    containerPolicies:
    - containerName: '*'    #Apply this policy to all containers in the pod
      minAllowed:
        cpu: 250m
        memory: 128Mi
      maxAllowed:
        cpu: 1Gi
        memory: 1.5Gi
